### ISSUE TITLE
Enhancement request: column headers

### ISSUE THREAD

**Issue by kseistrup** [ytoto/cjdc#1]
I like cjdc and use it daily.  However, it would be nice with column headers.  Apart from the `fc00::/8` addresses it is not obvious what information some of the other columns hold.

Cheers.

**Comment by ytoto** [comment]
Is that ok if I add a -v option to show the header ?

**Comment by kseistrup** [comment]
That's perfectly fine with me.

**Comment by ytoto** [comment]
I did it. Any other suggestions are welcome.
Thank you for your feedback.

**Comment by kseistrup** [comment]
Looks good, thanks! :)
