### ISSUE TITLE
I/O numbers?

### ISSUE THREAD

**Issue by kseistrup** [ytoto/cjdc#2]
This is not an issue as such, but I don't know how to contact you for questions…

The output from `cjdc p` displays I/O numbers in the Giga range, whereas `ifconfig tun0` shows less that 500 MiB total (I+O). It is unclear whether `cjdc` is showing bits or bytes, but even if it were bits the numbers far exceed those tallied by `tun0` itself.  Could you explain the discrepancy, please?

Cheers.

**Comment by ytoto** [comment]
well, I don't know the cjdns internals, but I think the traffic reported by cjdc includes the UDP traffic sent to others node on eth0 IPv4. So, maybe the sum of ifconfig eth0 + ifconfig tun0 numbers will be closer.

You can contact me on EFnet IRC, #MeshnetEurope,
or you can continue to post here as others can read this too.

**Comment by kseistrup** [comment]
Yes, someone on HypeIRC told me that the traffic on `tun0` didn't tell us the total amount of traffic routed.  So perhaps the numbers `cjdc` shows are fine.  I'm comfortable to close the issue here and leave the answer at that so that other can find it if they search.

Cheers.
